apiVersion: inspector.k8s/v1
kind: RulesConfig

# 通用配置
config:
  autoReload: true
  reloadInterval: "30s"
  environment: "prod"

# 集群环境映射
clusterEnvironments:
  "cluster-dev-01": "dev"
  "cluster-dev-02": "dev"
  "cluster-test-01": "test"
  "cluster-prod-01": "prod"
  "cluster-prod-02": "prod"
  "default": "prod"

# 规则列表
rules:
  # CPU相关规则
  - id: "high_cpu_utilization"
    name: "高CPU利用率"
    description: "节点CPU使用率过高"
    category: "node"
    severity: "warning"
    condition:
      metric: "cpu_utilization"
      operator: ">"
      threshold: 80
      thresholds:
        dev: 90
        test: 85
        prod: 80
    remediation: "考虑扩展集群或限制节点上的工作负载"
    enabled: true
  
  - id: "low_cpu_utilization"
    name: "低CPU利用率"
    description: "节点CPU使用率过低，可能存在资源浪费"
    category: "node"
    severity: "info"
    condition:
      metric: "cpu_utilization"
      operator: "<"
      threshold: 20
      thresholds:
        dev: 10
        test: 15
        prod: 20
    remediation: "考虑合并工作负载或降低节点规格"
    enabled: true
  
  - id: "high_cpu_allocation"
    name: "高CPU分配率"
    description: "节点CPU分配率过高，可能导致Pod调度失败"
    category: "node"
    severity: "warning"
    condition:
      metric: "cpu_allocation_rate"
      operator: ">"
      threshold: 90
      thresholds:
        dev: 95
        test: 90
        prod: 85
    remediation: "考虑扩展集群或限制节点上的工作负载"
    enabled: true

  # 内存相关规则
  - id: "high_memory_utilization"
    name: "高内存利用率"
    description: "节点内存使用率过高"
    category: "node"
    severity: "warning"
    condition:
      metric: "memory_utilization"
      operator: ">"
      threshold: 85
      thresholds:
        dev: 90
        test: 85
        prod: 80
    remediation: "考虑扩展集群或限制节点上的工作负载"
    enabled: true
  
  - id: "low_memory_utilization"
    name: "低内存利用率"
    description: "节点内存使用率过低，可能存在资源浪费"
    category: "node"
    severity: "info"
    condition:
      metric: "memory_utilization"
      operator: "<"
      threshold: 30
      thresholds:
        dev: 20
        test: 25
        prod: 30
    remediation: "考虑合并工作负载或降低节点规格"
    enabled: true
  
  - id: "high_memory_allocation"
    name: "高内存分配率"
    description: "节点内存分配率过高，可能导致Pod调度失败"
    category: "node"
    severity: "warning"
    condition:
      metric: "memory_allocation_rate"
      operator: ">"
      threshold: 90
      thresholds:
        dev: 95
        test: 90
        prod: 85
    remediation: "考虑扩展集群或限制节点上的工作负载"
    enabled: true

  # 存储相关规则
  - id: "high_storage_utilization"
    name: "高存储利用率"
    description: "节点临时存储使用率过高"
    category: "node"
    severity: "warning"
    condition:
      metric: "ephemeral_storage_utilization"
      operator: ">"
      threshold: 85
      thresholds:
        dev: 90
        test: 85
        prod: 80
    remediation: "清理节点上的临时文件或扩展存储容量"
    enabled: true
  
  - id: "high_storage_allocation"
    name: "高存储分配率"
    description: "节点临时存储分配率过高，可能导致Pod调度失败"
    category: "node"
    severity: "warning"
    condition:
      metric: "ephemeral_storage_allocation_rate"
      operator: ">"
      threshold: 90
      thresholds:
        dev: 95
        test: 90
        prod: 85
    remediation: "清理节点上的临时文件或扩展存储容量"
    enabled: true

  # Pod相关规则
  - id: "high_pod_density"
    name: "高Pod密度"
    description: "节点上运行的Pod数量接近上限"
    category: "node"
    severity: "warning"
    condition:
      metric: "pods_allocation_rate"
      operator: ">"
      threshold: 85
      thresholds:
        dev: 90
        test: 85
        prod: 80
    remediation: "考虑扩展集群，增加更多节点"
    enabled: true

  # 节点压力状态规则
  - id: "memory_pressure"
    name: "内存压力"
    description: "节点处于内存压力状态"
    category: "node"
    severity: "critical"
    condition:
      metric: "memory_pressure"
      operator: "=="
      threshold: true
    remediation: "立即检查节点上的工作负载，减少内存使用或扩展节点容量"
    enabled: true
  
  - id: "disk_pressure"
    name: "磁盘压力"
    description: "节点处于磁盘压力状态"
    category: "node"
    severity: "critical"
    condition:
      metric: "disk_pressure"
      operator: "=="
      threshold: true
    remediation: "清理节点上的磁盘空间或扩展存储容量"
    enabled: true
  
  - id: "pid_pressure"
    name: "PID压力"
    description: "节点处于PID压力状态，进程数量过多"
    category: "node"
    severity: "critical"
    condition:
      metric: "pid_pressure"
      operator: "=="
      threshold: true
    remediation: "检查并减少节点上的进程数量"
    enabled: true
  
  - id: "network_pressure"
    name: "网络压力"
    description: "节点处于网络压力状态"
    category: "node"
    severity: "critical"
    condition:
      metric: "network_pressure"
      operator: "=="
      threshold: true
    remediation: "检查网络配置和连接状态"
    enabled: true

  # 节点状态规则
  - id: "node_not_ready"
    name: "节点未就绪"
    description: "节点未处于就绪状态"
    category: "node"
    severity: "critical"
    condition:
      metric: "ready"
      operator: "=="
      threshold: false
    remediation: "检查节点的健康状态和kubelet服务"
    enabled: true 